# Generated by Django 4.2.2 on 2023-06-11 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_alter_login_log_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('pro_codigo', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('pro_valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pro_nome', models.CharField(max_length=25)),
                ('pro_tipo', models.CharField(max_length=25)),
                ('pro_qtde', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Login_Produto',
            fields=[
                ('lp_codigo', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('log_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.login')),
                ('pro_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produtos')),
            ],
        ),
    ]
