# Generated by Django 4.2.2 on 2023-06-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('log_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('log_email', models.CharField(max_length=25)),
                ('log_senha', models.CharField(max_length=25)),
            ],
        ),
    ]
