# Generated by Django 4.2.2 on 2023-06-10 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('cad_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('cad_nome', models.CharField(max_length=30)),
                ('cad_email', models.CharField(max_length=25, unique=True)),
                ('cad_rua', models.CharField(max_length=25)),
                ('cad_numero', models.CharField(max_length=10)),
                ('cad_bairro', models.CharField(max_length=25)),
                ('cad_cidade', models.CharField(max_length=25)),
                ('cad_contato', models.IntegerField(unique=True)),
                ('cad_senha', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='LoginCadastro',
            fields=[
                ('lc_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('cad_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro.cadastro')),
                ('log_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.login')),
            ],
        ),
    ]
