# Generated by Django 4.2.2 on 2023-06-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_cadastro_cad_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cad_contato',
            field=models.CharField(max_length=20),
        ),
    ]
