# Generated by Django 4.2.2 on 2023-06-11 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('con_codigo', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('con_nomePet', models.CharField(max_length=15)),
                ('con_tipoPet', models.CharField(max_length=10)),
                ('con_raca', models.CharField(max_length=10)),
                ('con_responsavel', models.CharField(max_length=25)),
                ('con_dia', models.DateField()),
                ('con_hora', models.TimeField()),
                ('age_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agendamentos.agendamentos')),
            ],
        ),
        migrations.CreateModel(
            name='Banhoetosa',
            fields=[
                ('bet_codigo', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('bet_nomePet', models.CharField(max_length=15)),
                ('bet_tipoPet', models.CharField(max_length=10)),
                ('bet_raca', models.CharField(max_length=10)),
                ('bet_responsavel', models.CharField(max_length=25)),
                ('bet_dia', models.DateField()),
                ('bet_hora', models.TimeField()),
                ('age_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agendamentos.agendamentos')),
            ],
        ),
        migrations.CreateModel(
            name='Adestramento',
            fields=[
                ('ade_codigo', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('ade_nomePet', models.CharField(max_length=15)),
                ('ade_tipoPet', models.CharField(max_length=10)),
                ('ade_raca', models.CharField(max_length=10)),
                ('ade_responsavel', models.CharField(max_length=25)),
                ('ade_dia', models.DateField()),
                ('ade_hora', models.TimeField()),
                ('age_codigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agendamentos.agendamentos')),
            ],
        ),
    ]
