# Generated by Django 4.2.2 on 2023-06-13 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('servicos', '0002_alter_adestramento_age_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adestramento',
            name='age_codigo',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to='agendamentos.agendamentos'),
            preserve_default=False,
        ),
    ]
