# Generated by Django 4.2.2 on 2023-06-13 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('servicos', '0003_alter_adestramento_age_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adestramento',
            name='ade_raca',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='banhoetosa',
            name='age_codigo',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to='agendamentos.agendamentos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banhoetosa',
            name='bet_raca',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='age_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agendamentos.agendamentos'),
        ),
        migrations.AlterField(
            model_name='consultas',
            name='con_raca',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
